# This workflow will publish the package to npm when a release is created or a tag is pushed

name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm run test
        
      - name: Build package
        run: npm run build
        
      - name: Get package version
        id: package-version
        run: echo "version=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - name: Create git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ steps.package-version.outputs.version }}
          git push origin ${{ steps.package-version.outputs.version }}
